In [1]:
import numpy as np

In [2]:
np1 = np.arange(1000000)

In [3]:
%time for _ in range(100): np1 *=2

CPU times: total: 62.5 ms
Wall time: 72.7 ms


In [4]:
list1 = list(range(1000000))

In [5]:
# %time for _ in range(100): list1  = [x*2 for x in list1]

In [6]:
km = np.array([40,50,30,0,60])
años = np.array([2003,1991,1990,2019,2006])

In [7]:
resultado = 2023 - años
resultado

array([20, 32, 33,  4, 17])

In [8]:
media = km  / resultado
media

array([2.        , 1.5625    , 0.90909091, 0.        , 3.52941176])

In [9]:
40/20

2.0

In [10]:
datos = np.array([km, años])
datos

array([[  40,   50,   30,    0,   60],
       [2003, 1991, 1990, 2019, 2006]])

In [11]:
resultado = datos[0] / (2023 - datos[1])
resultado

array([2.        , 1.5625    , 0.90909091, 0.        , 3.52941176])

In [12]:
resultado = datos[0] * datos[1]
resultado

array([ 80120,  99550,  59700,      0, 120360])

In [13]:
resultado = datos[0] + datos[1]
resultado

array([2043, 2041, 2020, 2019, 2066])

In [14]:
resultado = datos[0] - datos[1]
resultado

array([-1963, -1941, -1960, -2019, -1946])

In [15]:
# IMC = peso / altura ^ 2

In [16]:
datos = np.array([km, años])
datos

array([[  40,   50,   30,    0,   60],
       [2003, 1991, 1990, 2019, 2006]])

In [17]:
datos[0][2]

30

In [18]:
datos[1][2]

1990

In [19]:
lista = np.arange(50)
lista

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [20]:
lista[10:41:2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [21]:
lista[1::2]
# selecciona los impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49])

In [22]:
lista[::2]
# selecciona los pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [23]:
datos

array([[  40,   50,   30,    0,   60],
       [2003, 1991, 1990, 2019, 2006]])

In [24]:
datos[0][2:]

array([30,  0, 60])

In [25]:
datos[1][::2]

array([2003, 1990, 2006])

In [26]:
datos[datos > 1991]

array([2003, 2019, 2006])

In [27]:
datos[datos < 50]

array([40, 30,  0])

In [28]:
carros = datos[0]

In [29]:

datos[:2, :2]

array([[  40,   50],
       [2003, 1991]])

In [30]:
contador=np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [32]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
contador.reshape((5,2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [34]:
km = [40,50,30,0,60]
años = [2003,1991,1990,2019,2006]

In [35]:
info = km + años
info

[40, 50, 30, 0, 60, 2003, 1991, 1990, 2019, 2006]

In [36]:
np.array(info).reshape((2,5))

array([[  40,   50,   30,    0,   60],
       [2003, 1991, 1990, 2019, 2006]])

In [37]:
np.array(info).reshape((5,2),order='F')

array([[  40, 2003],
       [  50, 1991],
       [  30, 1990],
       [   0, 2019],
       [  60, 2006]])

In [38]:
datos = np.array(
    [
        ['Roberto', 'casado', 'masculino'],
        ['Sheila', 'soltero', 'femenino'],
        ['Bruno', 'soltero', 'masculino'],
        ['Rita', 'casado', 'femenino']
    ]
)

In [39]:
datos1 = datos.copy()

In [40]:
datos1.resize((10,10), refcheck=False)
datos1

array([['Roberto', 'casado', 'masculino', 'Sheila', 'soltero',
        'femenino', 'Bruno', 'soltero', 'masculino', 'Rita'],
       ['casado', 'femenino', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '']], dtype='<U9')

In [41]:
datos1[5][0] = 'Neo777'
datos1[9][0] = 'Pam666'
datos1

array([['Roberto', 'casado', 'masculino', 'Sheila', 'soltero',
        'femenino', 'Bruno', 'soltero', 'masculino', 'Rita'],
       ['casado', 'femenino', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['Neo777', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', ''],
       ['Pam666', '', '', '', '', '', '', '', '', '']], dtype='<U9')

In [42]:
# datos = np.array(
#     [
#         ['Roberto', 'casado', 'masculino'],
#         ['Sheila', 'soltero', 'femenino'],
#         ['Bruno', 'soltero', 'masculino'],
#         ['Rita', 'casado', 'femenino']
#     ]
# )

datos = np.array(
    [
        ['KKK111', '', ''],
       
    ]
)

In [43]:
datos_new = datos.copy()

In [44]:
datos_new.resize((10,20), refcheck=False)
datos_new

array([['KKK111', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '']], dtype='<U6')

In [45]:
datos_new[7][0]='KEM311'
datos_new[5][5]='NEO777'
datos_new[9][15]='SAM666'
datos_new[-1][0]='KEM222'
datos_new[3][5]='NEO444'
datos_new[0][15]='SAM333'
datos_new

array([['KKK111', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        'SAM333', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', 'NEO444', '', '', '', '', '', '', '', '', '',
        '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['', '', '', '', '', 'NEO777', '', '', '', '', '', '', '', '', '',
        '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['KEM311', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', '', ''],
       ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        '', '', '', ''],
       ['KEM222', '', '', '', '', '', '', '', '', '', '', '', '', '', '',
        'SAM666', '', '

In [46]:
años = np.loadtxt(fname='carros-años.txt')
km = np.loadtxt(fname='carros-km.txt')
valor = np.loadtxt(fname='carros-valor.txt')

In [50]:
ds = np.column_stack((años, km, valor))
ds

array([[2.0030000e+03, 4.4410000e+04, 8.8078640e+04],
       [1.9910000e+03, 5.7120000e+03, 1.0616194e+05],
       [1.9900000e+03, 3.7123000e+04, 7.2832160e+04],
       [2.0200000e+03, 0.0000000e+00, 1.2454907e+05],
       [2.0060000e+03, 2.5757000e+04, 9.2612100e+04],
       [2.0120000e+03, 1.0728000e+04, 9.7497730e+04],
       [2.0200000e+03, 0.0000000e+00, 5.6445200e+04],
       [2.0090000e+03, 7.7599000e+04, 1.1231044e+05],
       [2.0100000e+03, 9.9197000e+04, 1.2071627e+05],
       [2.0110000e+03, 3.7978000e+04, 7.6566490e+04],
       [2.0020000e+03, 1.2859000e+04, 7.1647590e+04],
       [2.0070000e+03, 8.0520000e+03, 7.3919530e+04],
       [2.0010000e+03, 8.9773000e+04, 1.1273299e+05],
       [2.0200000e+03, 0.0000000e+00, 5.3183380e+04],
       [2.0090000e+03, 4.1457000e+04, 1.2748842e+05],
       [2.0160000e+03, 1.1560700e+05, 5.9910400e+04],
       [2.0120000e+03, 4.6449000e+04, 6.1118590e+04],
       [2.0200000e+03, 0.0000000e+00, 8.8552390e+04],
       [2.0160000e+03, 3.708

In [51]:
ds.shape

(258, 3)

In [64]:
media_kilometros = np.mean(ds[::,1])
media_kilometros

44499.41472868217

In [65]:
media_valor = np.mean(ds[::,2])
round(media_valor, 2)

98960.51

In [62]:
np.mean(ds, axis = 0)

array([ 2007.74806202, 44499.41472868, 98960.51310078])

In [66]:
media_kilometros = np.std(ds[::,1])
media_kilometros

39859.82699005149

In [67]:
media_valor = np.std(ds[::,2])
round(media_valor, 2)

29754.1

In [70]:
ds.sum(axis=0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [71]:
np.sum(ds, axis=0)

array([  517999.        , 11480849.        , 25531812.37999999])

In [72]:
np.sum(ds[::, 2])

25531812.38

In [73]:
import pandas as pd

In [84]:
df = pd.DataFrame(data=ds, columns=['años','km', 'valor'])
result = df.groupby('años').mean()
result.head(10)

km         valor
años                              
1990.0  72083.666667  96116.206667
1991.0  47036.444444  93420.658889
1992.0  51283.000000  90670.667500
1993.0  55384.250000  93357.635000
1994.0  70260.777778  96623.326667
1995.0  71289.714286  86117.702857
1996.0  50926.100000  98619.528000
1997.0  71897.000000  96852.883333
1998.0  71828.000000  97801.913333
1999.0  39075.500000  98675.220000